[Interface]
PrivateKey = RbycCTD6Omja+hkG6+vgvfrzR82i95qwseyPhNHPFMM=
Address = 12.11.10.17/32
DNS = 8.8.8.8

[Peer]
PublicKey = RkAaRP6u0k7GydeT+wWOJjGr1JQaH4/6DqYg3w9s4TQ=
AllowedIPs = 0.0.0.0/0
Endpoint = s20.arta20.xyz:11588
PersistentKeepalive = 10